OQ-10-Create-a-Form
GiuseppeArbore/polito-se2-24-18 pull request #7
Opened 2024-10-09 21:09 UTC by golnazsaraji

it's actually about showing the list of service types to the customer

2024-10-10 08:06 UTC, lbordino commented on client/src/Components/Customer/Service/Service.scss
> +  font-family: 'Gloria Hallelujah';
can u change the font to something more "classic"

2024-10-14 20:58 UTC, lbordino commented on client/src/App.tsx
> +// import reactLogo from './assets/react.svg';
delete

2024-10-14 21:01 UTC, lbordino commented on client/src/Components/Customer/Service/Services.tsx
> +    const [serviceId, setServiceId] = useState<number>(0);
are we sure that there is a 0 service? Whenever the page refresh it sends 2 calls to get service 0

2024-10-14 21:05 UTC, lbordino commented on server/src/errors/servicesError.ts
> +        this.customCode = 401;
this is a 409 conflict

2024-10-14 21:06 UTC, lbordino commented on server/src/routes.ts
> +    // app.get("/queue/number", async (req, res) => {
delete

2024-10-14 21:07 UTC, lbordino requested changes
Remove all the unused code, font and images. I've attached some comments to refactor the code

2024-10-15 18:39 UTC, golnazsaraji commented on client/src/App.tsx
> +// import reactLogo from './assets/react.svg';
done

2024-10-15 18:42 UTC, golnazsaraji commented on server/src/routes.ts
> +    // app.get("/queue/number", async (req, res) => {
done

2024-10-15 20:50 UTC, lbordino approved these changes

2024-10-15 20:52 UTC, merged

2024-10-15 20:53 UTC, golnazsaraji commented
create the service list for customer